/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "project-gestion-mdp-OSJNa741hX1UOh3Q8C54U8uAmuC3joCy",
  "version": "2020-11-20"
}

export default ebconfig;